name: Test med UV
on: [push]
jobs:
  ExecuteTest:
    runs-on: ubuntu-latest
    steps:
      - name: hent kode
        uses: actions/checkout@v6
      - name: installer uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.1"
      - name: installer python
        run: uv python install
      - name: test
        run: uv run pytest tests/
