name: Test med pip
on: [push]
jobs:
  ExecuteTest:
    runs-on: ubuntu-latest
    steps:
      - name: hent kode
        uses: actions/checkout@v6
      - name: installer python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.14'
          cache: 'pip'
      - name: installer pakker
        run: pip install -r requirements.txt
      - name: test
        run: python -m pytest tests/
